### ISSUE TITLE
No logo shown in any movie views

### ISSUE THREAD

**Issue by bartolomesoriano** [MadMikeDoc/skin.aeon.madnox#127]
I tried with showcase, kodiflix, tripanel, wall and others.  Seems related to changes done yesterday, March 2nd.

**Comment by MadMikeDoc** [comment]
I think this is the problem in variables.xml from yesterday, someone needs to change this line

`<value>$INFO[Window(Home).Property(SkinHelper.Music.ClearLogo)]</value>`

to 

`<value` condition="Container.Content(albums) | Container.Content(artists) | Container.Conter(songs)">$INFO[Window(Home).Property(SkinHelper.Music.ClearLogo)]</value>

At the moment it is just defaulting to this due to no condition and this stops the following line $VAR[LogoVarList] from executing.

Mike, when setting up vars it's a first come, first server basis so it checks the values one by one and once one it true that's it, and this one will always be true as there are no conditions.

Also, is you change in replacement of the first 2 or in addition to the 2 music logo checks?

Mike

**Comment by meowmoo** [comment]
My fault sorry, was testing a few things and forgot to remove it again....

Change it as soon as I'm home

**Comment by meowmoo** [comment]
fixed 65d1e0b
